services:
  cloudflared:
    image: cloudflare/${CLOUDFLARED_VERSION}
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    user: "1000:1000"
    networks:
      - iot_net
    cap_add:
      - NET_RAW

  iot_postgres:
    image: postgres:${IOT_POSTGRES_VERSION}
    container_name: iot_postgres_service
    restart: unless-stopped
    networks:
      - iot_db_net
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

  iot_api:
    image: api_service:latest
    restart: unless-stopped
    networks:
      - iot_net
      - iot_db_net
    depends_on:
      - postgres

networks:
  public_access:
    driver: bridge
  iot_net:
    driver: bridge
  iot_db_net: 
    driver: bridge
