# Centralized Cloudflared Service
# This runs as a separate service that connects to all networks
services:
  cloudflared:
    image: cloudflare/cloudflared:${CLOUDFLARED_VERSION:-latest}
    container_name: cloudflared_tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      #- iot_network
      - notes_network
      - drive_network
      - obsidian_network
      - signaturepdf_network
      - immich_network
    # Healthcheck to ensure tunnel is working
    healthcheck:
      test:
        ["CMD", "cloudflared", "tunnel", "--metrics", "0.0.0.0:2000", "ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# External networks that are created by other compose files
networks:
  #iot_network:
  #  external: true
  #  name: iot_network
  notes_network:
    external: true
    name: notes_network
  drive_network:
    external: true
    name: drive_network
  obsidian_network:
    external: true
    name: obsidian_network
  signaturepdf_network:
    external: true
    name: signaturepdf_network
  immich_network:
    external: true
    name: immich_network
