services:
  couchdb-obsidian-livesync:
    container_name: obsidian-livesync
    image: couchdb:3.3.3
    environment:
      - PUID=99
      - PGID=100
      - UMASK=0022
      - TZ=Europe/Berlin
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ${COUCHDB_DATA_PATH}:/opt/couchdb/data
      - ${COUCHDB_CONFIG_PATH}:/opt/couchdb/etc/local.d
    ports:
      - "5984:5984"
    restart: unless-stopped
