# Cloudflare Tunnel Configuration
# This configuration defines how traffic is routed from your public domains to internal services

# Logging configuration
loglevel: info

# Connection settings
metrics: 0.0.0.0:2000
no-autoupdate: true

# Ingress rules define how traffic is routed from public hostnames to your internal services
# Rules are processed in order - first match wins
# IMPORTANT: The catch-all rule must be last
ingress:
  # Rules for IoT services under iot.atlantis-cloud.com
  # API endpoint
  - hostname: iot.atlantis-cloud.com
    path: /api/*
    service: http://iot_api:8000
    originRequest:
      httpHostHeader: iot.atlantis-cloud.com
      connectTimeout: 30s
      tlsTimeout: 10s
      noTLSVerify: false

  # Dashboard endpoint
  - hostname: iot.atlantis-cloud.com
    path: /dashboard/*
    service: http://iot_dashboard:3001
    originRequest:
      httpHostHeader: iot.atlantis-cloud.com
      connectTimeout: 30s
      tlsTimeout: 10s
      noTLSVerify: false

  # Default for iot.atlantis-cloud.com (redirect to dashboard)
  - hostname: iot.atlantis-cloud.com
    service: http://iot_dashboard:3001
    originRequest:
      httpHostHeader: iot.atlantis-cloud.com
      connectTimeout: 30s
      tlsTimeout: 10s
      noTLSVerify: false

  # Rule for Affine (Notes) service
  - hostname: notes.atlantis-cloud.com
    service: http://affine:3010
    originRequest:
      httpHostHeader: notes.atlantis-cloud.com
      connectTimeout: 30s
      tlsTimeout: 10s
      noTLSVerify: false

  # Rule for Nextcloud (Drive) service
  - hostname: drive.atlantis-cloud.com
    service: http://nextcloud:80
    originRequest:
      httpHostHeader: drive.atlantis-cloud.com
      connectTimeout: 30s
      tlsTimeout: 10s
      noTLSVerify: false

  # Rule for Obsidian LiveSync CouchDB
  - hostname: obsidian.atlantis-cloud.com
    service: http://obsidian-livesync:5984
    originRequest:
      httpHostHeader: obsidian.atlantis-cloud.com
      connectTimeout: 30s
      tlsTimeout: 10s
      noTLSVerify: false

  # Rule for SignaturePDF service
  - hostname: pdf.atlantis-cloud.com
    service: http://signaturepdf:80
    originRequest:
      httpHostHeader: pdf.atlantis-cloud.com
      connectTimeout: 30s
      tlsTimeout: 10s
      noTLSVerify: false

  # Rule for Immich (Photos) service
  - hostname: photos.atlantis-cloud.com
    service: http://immich-server:3001
    originRequest:
      httpHostHeader: photos.atlantis-cloud.com
      connectTimeout: 30s
      tlsTimeout: 10s
      noTLSVerify: false

  # Catch-all rule - returns 404 for unmatched requests
  # This MUST be the last rule
  - service: http_status:404
