# This is the configuration file for the Cloudflare Tunnel.
# It should be placed in ./cloudflared/config.yml relative to your docker-compose/template file.

# Ingress rules define how traffic is routed from public hostnames to your internal services.
ingress:
  # Rules for services under iot.atlantis-cloud.com
  # API
  #- hostname: iot.atlantis-cloud.com
  #  path: /api(/.*)?
  #  service: http://iot_api:8000
  # Dashboard
  #- hostname: iot.atlantis-cloud.com
  #  path: /dashboard(/.*)?
  #  service: http://iot_dashboard:3001

  # Rule for your Affine (Notes) service
  # Assumes 'affine' service listens on port 3000 internally
  - hostname: notes.atlantis-cloud.com
    service: http://affine:3000

  # Rule for your Nextcloud (Drive) service
  # Assumes 'nextcloud' service listens on port 80 internally
  - hostname: drive.atlantis-cloud.com
    service: http://nextcloud:80

  # Rule for Obsidian LiveSync CouchDB
  # Assumes 'obsidian-livesync' service listens on port 5984 internally
  - hostname: obsidian.atlantis-cloud.com
    service: http://obsidian-livesync:5984

  # This is a catch-all rule. If no other hostname matches,
  # it will return a 404 error. This must be the last rule.
  - service: http_status:404
